# Generated by Django 4.0.4 on 2022-05-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='year',
            new_name='counters',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
