# Generated by Django 4.0.4 on 2022-05-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_client_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='livre',
        ),
    ]
