# Generated by Django 4.0.4 on 2022-05-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_product_livre'),
    ]

    operations = [
        migrations.CreateModel(
            name='livres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='livre',
        ),
    ]
