# Generated by Django 4.0.4 on 2022-05-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_livres_delete_livre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='livres',
            new_name='livre',
        ),
    ]
